language: java
sudo: required
matrix:
  include:
    - jdk: oraclejdk8

script: >-
    ./config/travis/run-checks.sh &&
    travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls

before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"
          - export TZ=Asia/Tokyo

addons:
  apt:
    packages:
      - oracle-java8-installer
